export const WORDS_CHUNK_LENGTH = 20;
export const WORDS_CHUNK_PAGES_QUANTITY = 20;
export const ANSWERS_QUANTITY = 5;
export const INCORRECT_ANSWERS_QUANTITY = 3;
export const MAX_INCORRECT_ANSWERS_TO_LOOSE = 5;

export const ANSWER_BUTTON_DELAY = 500;
