import { ITeamItem } from '../../../core/interfaces/iteam-item';

export const LIST_TEAM: ITeamItem[] = [
  {
    id: 0,
    imgUrl: './assets/img/home/team1.jpg',
    name: 'Олег',
    position: 'тимлид',
    description: 'описание что-нибудь о человеке и его работе в команде и над проектом',
    link: 'https://github.com/olegbukalov',
  },
  {
    id: 1,
    imgUrl: './assets/img/home/team2.jpg',
    name: 'Александр',
    position: 'разработчик',
    description: 'описание что-нибудь о человеке и его работе в команде и над проектом',
    link: 'https://github.com/oubowen',
  },
  {
    id: 2,
    imgUrl: './assets/img/home/team3.jpg',
    name: 'Юра',
    position: 'разработчик',
    description: 'описание что-нибудь о человеке и его работе в команде и над проектом',
    link: 'https://github.com/yurakuzmich',
  },
  {
    id: 3,
    imgUrl: './assets/img/home/team4.jpg',
    name: 'Кирилл',
    position: 'разработчик',
    description: 'описание что-нибудь о человеке и его работе в команде и над проектом',
    link: 'https://github.com/kirillbuzov73',
  },
  {
    id: 4,
    imgUrl: './assets/img/home/team5.jpg',
    name: 'Алексей',
    position: 'разработчик',
    description: 'описание что-нибудь о человеке и его работе в команде и над проектом',
    link: 'https://github.com/vanessagrapefruit',
  },
  {
    id: 5,
    imgUrl: './assets/img/home/team6.jpg',
    name: 'Марина',
    position: 'разработчик',
    description: 'описание что-нибудь о человеке и его работе в команде и над проектом',
    link: 'https://github.com/mig-marina',
  },
  {
    id: 6,
    imgUrl: './assets/img/home/team7.jpg',
    name: 'Аня',
    position: 'ментор',
    description: 'описание что-нибудь о человеке и его работе в команде и над проектом',
    link: '',
  },
];
